config/routes.rb
Rails.application.routes.draw do
  get '/' => "main#index"
  post "update" => "main#update"
  get "show" => "main#show"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/update.rb
class Update
    include ActiveModel::Model
    #要素を定義します
    attr_accessor :lat, :lng ,:range ,:smoking
    #バリデーションの定義
    validates :lat, presence: true
    validates :lng, presence: true
    validates :range, presence: true
    validates :smoking, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    def au
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  require 'net/http'
  require 'uri'
  require 'json'

  

  def index


  end

def update
  session[:address] = params[:address]
  session[:smoking] = params[:smoking]
  session[:key] = "a53d2b44f8d80d6d"
  session[:keyword] = "居酒屋"
  session[:format] = "json"
 
  redirect_to "/show"
end

  def show
  
    data = {
      "key": session[:key],
      "address": session[:address],
      "keyword": session[:keyword],
      "non_smoking": session[:smoking],
      "format": session[:format]
    }

    query = data.to_query
  uri = URI.parse('http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?' + query )
    res = Net::HTTP.get_response(uri)
   hash = JSON.parse(res.body,symbolize_names: true)

   @results = hash[:results][:shop]
   
   @result = hash[:results][:shop].sort_by{rand}[0]





    end

 # 200 Success
def response_success(class_name, action_name)
  render status: 200, json: { status: 200, message: "Success #{class_name.capitalize} #{action_name.capitalize}" }
end

# 400 Bad Request
def response_bad_request
  render status: 400, json: { status: 400, message: 'Bad Request' }
end

# 401 Unauthorized
def response_unauthorized
  render status: 401, json: { status: 401, message: 'Unauthorized' }
end

# 404 Not Found
def response_not_found(class_name = 'page')
  render status: 404, json: { status: 404, message: "#{class_name.capitalize} Not Found" }
end

# 409 Conflict
def response_conflict(class_name)
  render status: 409, json: { status: 409, message: "#{class_name.capitalize} Conflict" }
end

# 500 Internal Server Error
def response_internal_server_error
  render status: 500, json: { status: 500, message: 'Internal Server Error' }
end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IzakayaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>居酒屋ファインダー</h1>

<body>

<p>検索条件を指定してください</p>

<%= form_with url: update_path do |f| %>

<li>最寄りの駅</li>
<%=f.select :address,[["川崎","川崎"],["鶴見","鶴見"],["綱島","綱島"],["蒲田","蒲田"]]%>
<br><br>

<li>喫煙</li>
<%=f.select :smoking,[["禁煙","0"],["喫煙","1"]]%>
<br><br>

<%=f.submit "検索"%>
<%end%>

</body>
<br><br><br>
Powered by <a style="text-align:right" href="http://webservice.recruit.co.jp/">ホットペッパー Webサービス</a>

app/views/main/show.html.erb
<h1>ここの居酒屋にいこう！</h1>


<%=@result%>

<% @results.each do |result| %>
<br>
<p><%=result[:name]%></p>

<body>
<br>
<%=result[:open]%>
<br>
<%=result[:access]%>
<br>
<%=result[:address]%>
<br>
<%=result[:budget][:average]%>
<br>
<%= image_tag "#{result[:photo][:pc][:l]}",:width => '450',:height => '300'%>
<br>
お店のURLはこちら→<%=link_to"#{result[:urls][:pc]}"%>

<%end%>


<br><br>
<a href="show" class="btn-square">同じ条件でもう一度検索</a>
<br><br>
<a href="/" class="btn-square">条件を変えてもう一度検索</a>

</body>
<br><br><br>
 Powered by <a style="text-align:right" href="http://webservice.recruit.co.jp/">ホットペッパー Webサービス</a>